### ISSUE TITLE
If Platform Proxy is set, it can't be explicitly unset in replications

### ISSUE THREAD

**Issue by OliverOlg** [jfrog/terraform-provider-artifactory#1088]
**Describe the bug**
If you have a platform Proxy configured leaving the `proxy` empty or '= null' in the local_repository_multi_replication will result in the Platform default proxy being set. It's not possible to have no proxy set in this scenario, since artifactory will default to setting the platform proxy.

```
resource "artifactory_local_repository_multi_replication" "repo-local" {
    repo_key = "repo-local"
    cron_exp = "0 0 12 * * ? *"
    enable_event_replication = true

    replication {
        enabled = true
        url = "https://remote.artifactory/artifactory/repo-local"
        username = user
        password = password
        sync_deletes = true
        sync_statistics = true
        sync_properties = true
        # proxy = null
    }
}
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
7.84.20
- [x] Your version of terraform
Terraform v1.5.7
- [x] Your version of terraform provider
12.1.0, but this hasn't worked in 9.3.0 either

**Expected behavior**
Setting proxy = null should result in the replication having no proxy.

**Additional context**
Since the provider does not implement the disableProxy that is available since 7.41.7 in the [replication json 
](https://jfrog.com/help/r/jfrog-rest-apis/replication-configuration-json), it's not possible to create a replication that explicitly does not use a proxy.
