### ISSUE TITLE
"GetResourceIdentitySchemas Not Implemented" error with Terraform 1.12.1

### ISSUE THREAD

**Issue by ehartmann** [jfrog/terraform-provider-artifactory#1271]
**Describe the bug**

When upgrading to Terraform **1.12.1**, we are experiencing an error when trying to use the **v12.9.4**.
For information, the Artifactory provider is working correctly with Terraform **1.12.0**.

We are using Artifactory Cloud.

When trying to do a simple `terraform plan`, here is the error we are observing this error:
```
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider
│ registry.terraform.io/jfrog/platform: failed to retrieve schema from provider "registry.terraform.io/jfrog/platform":
│ Provider GetResourceIdentitySchemas Not Implemented: A GetResourceIdentitySchemas call was received by the provider, however
│ the provider does not implement the call. Either upgrade the provider to a version that implements resource identity support
│ or this is a bug in Terraform that should be reported to the Terraform maintainers...
╵
```

**Expected behavior**
The plugin should load without this exception.

**Additional context**
It seems to be a breaking change and here is the reported issue on the Kubernetes provider: https://github.com/hashicorp/terraform-provider-kubernetes/issues/2732 and the PR that fixes this issue: https://github.com/hashicorp/terraform-provider-kubernetes/pull/2733
